version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      time: "04:00"
      timezone: Asia/Tokyo
    labels:
      - automation
      - dependencies

  - package-ecosystem: npm
    directory: /doc
    schedule:
      interval: weekly
      day: monday
      time: "04:30"
      timezone: Asia/Tokyo
    labels:
      - automation
      - dependencies
    groups:
      patches:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    cooldown:
      default-days: 3
