# SPDX-FileCopyrightText: 2024-2025 Akira Komamura
# SPDX-License-Identifier: Unlicense
odig-odoc:
    odig odoc

sherlodoc-index: odig-odoc
    find "${ODIG_CACHE_DIR}/odoc" -name '*.odocl' \
    | grep -v '__' \
    | xargs sherlodoc index

sherlodoc-serve:
    sherlodoc serve
