# SPDX-License-Identifier: Unlicense
name: Build the Nix package

on:
  pull_request:
    paths-ignore:
      - 'README.*'
      - 'docs/**'

  push:
    branches:
      - master
    paths-ignore:
      - 'README.*'
      - 'docs/**'

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          # - ubuntu-24.04-arm
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Set up Nix
        uses: ./.github/actions/setup
        # with:
        #   cachix-token: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Build the package
        run: nix build -L

      # Use this if the flake exposes multiple packages to build.
      # See https://github.com/NixOS/nix/issues/7165

      # - name: Build the packages
      #   run: nix build ".#packages.$(nix eval --expr builtins.currentSystem --impure --raw).*" -L --option keep-going true

      # Alternatively, you can run `nix flake check` to perform multiple checks.

      # - name: Check the flake
      #   run: nix flake check -L --option keep-going true
