name: Build the Nix package

on:
  pull_request:
    paths-ignore:
      - 'README.*'
      - 'docs/**'

  push:
    branches:
      - master
    paths-ignore:
      - 'README.*'
      - 'docs/**'

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@V30
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - uses: cachix/cachix-action@v15
        with:
          name: akirak
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Build the package
        run: nix build
