# SPDX-License-Identifier: MIT
name: Set up Nix

description: Set up Nix with cachix enabled

inputs:
  cachix-token:
    description: Auth token for cachix
    required: true

runs:
  using: composite
  steps:
    - uses: cachix/install-nix-action@v31
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
        extra_nix_config:
          flake-registry =  https://raw.githubusercontent.com/akirak/flake-pins/master/registry.json

    - uses: cachix/cachix-action@v17
      with:
        name: akirak
        authToken: '${{ inputs.cachix-token }}'
        pushFilter: '-source$'
