# SPDX-License-Identifier: Unlicense
name: Install dependencies

description: Set up Nix with a GH-native cache enabled

inputs:
  cache-key:
    description: Suffix for the cache key to distinguish the package set
    type: string
    required: true

runs:
  using: composite
  steps:
    - uses: nixbuild/nix-quick-install-action@1f095fee853b33114486cfdeae62fa099cda35a9 # v33
      with:
        nix_conf: |
          keep-env-derivations = true
          keep-outputs = true

    - name: Restore the package cache
      uses: nix-community/cache-nix-action@135667ec418502fa5a3598af6fb9eb733888ce6a # v6
      with:
        primary-key: nix-${{ runner.os }}-${{ hashFiles('**/flake.lock', '**/pnpm-lock.yaml') }}-${{ inputs.cache-key }}
        restore-prefixes-first-match: nix-${{ runner.os }}-
        gc-max-store-size-linux: 1G
        paths: |
          node_modules/.pnpm
          # .output
          # ~/.cache/ms-playwright

    - name: Check the node version
      shell: bash
      run: nix develop -L -c sh -x -c 'node --version'

    - name: Install npm dependencies
      shell: bash
      run: nix develop -L -c pnpm install
