name: Run all check workflows

permissions:
  contents: read

on:
  workflow_dispatch:
  repository_dispatch:
    types:
    - check

jobs:
  check-elixir-app:
    uses: ./.github/workflows/check-elixir-app.yml

  check-elixir:
    uses: ./.github/workflows/check-elixir.yml

  check-flake-parts:
    uses: ./.github/workflows/check-flake-parts.yml

  check-flake-utils:
    uses: ./.github/workflows/check-flake-utils.yml

  check-gleam:
    uses: ./.github/workflows/check-gleam.yml

  check-go:
    uses: ./.github/workflows/check-go.yml

  check-java:
    uses: ./.github/workflows/check-java.yml

  check-minimal:
    uses: ./.github/workflows/check-minimal.yml

  check-node-typescript:
    uses: ./.github/workflows/check-node-typescript.yml

  check-ocaml-basic:
    uses: ./.github/workflows/check-ocaml-basic.yml

  check-ocaml-dune:
    uses: ./.github/workflows/check-ocaml-dune.yml

  check-pre-commit:
    uses: ./.github/workflows/check-pre-commit.yml

  check-python-uv-simple:
    uses: ./.github/workflows/check-python-uv-simple.yml

  check-rust:
    uses: ./.github/workflows/check-rust.yml

  check-treefmt:
    uses: ./.github/workflows/check-treefmt.yml

  check-typescript-effect:
    uses: ./.github/workflows/check-typescript-effect.yml

  check-zig:
    uses: ./.github/workflows/check-zig.yml
