name: "Auto-merge PR"

on:
  # zizmor: ignore[dangerous-triggers] This workflow is safe unless modified
  pull_request_target:

permissions:
  {}

jobs:
  merge:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: read

    steps:
      - uses: actions/create-github-app-token@1b10c78c7865c340bc4f6099eb2f838309f1e8c3 # v3
        id: generate-token
        with:
          app-id: ${{ secrets.CREATE_PR_APP_ID }}
          private-key: ${{ secrets.CREATE_PR_APP_PRIVATE_KEY }}
          permission-contents: write
          permission-pull-requests: write

      - name: Dependabot metadata
        id: dependabot-metadata
        uses: dependabot/fetch-metadata@25dd0e34f4fe68f24cc83900b1fe3fe149efef98 # v3
        with:
          github-token: ${{ github.token }}

      - name: Merge
        if: steps.dependabot-metadata.outputs.update-type == 'version-update:semver-patch'
        run: |
          gh pr merge "$PR_URL" --delete-branch --squash --auto
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
