name: "Auto-merge PR"

on:
  pull_request_target:

permissions:
  {}

jobs:
  merge:
    if: |
      github.actor == 'dependabot[bot]' &&
      github.event.pull_request.user.login == 'dependabot[bot]'

    runs-on: ubuntu-latest

    permissions:
      pull-requests: read

    steps:
      - uses: actions/create-github-app-token@v3
        id: generate-token
        with:
          app-id: ${{ secrets.CREATE_PR_APP_ID }}
          private-key: ${{ secrets.CREATE_PR_APP_PRIVATE_KEY }}
          permission-contents: write
          permission-pull-requests: write

      - name: Dependabot metadata
        id: dependabot-metadata
        uses: dependabot/fetch-metadata@v3
        with:
          github-token: ${{ github.token }}

      - name: Merge
        if: steps.dependabot-metadata.outputs.update-type == 'version-update:semver-patch'
        run: |
          gh pr merge "$PR_URL" --delete-branch --merge --auto
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
