name: Build and publish documentation

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'doc/**'
  push:
    branches:
      - master
    paths:
      - 'doc/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-upload:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v4
        name: Install pnpm
        with:
          version: 10.32.1
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v6
        with:
          node-version: 24
          cache: 'pnpm'
          cache-dependency-path: 'doc/pnpm-lock.yaml'

      - name: Install dependencies
        working-directory: doc
        run: pnpm install

      - name: Build documentation
        working-directory: doc
        run: pnpm run build

      - uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5.0.0
        with:
          path: doc/dist

  deploy:
    needs: build-and-upload
    if: ${{ github.ref == 'refs/heads/master' }}

    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5.0.0
