name: Check node-typescript

on:
  push:
    paths:
      - node-typescript/**
      - .github/workflows/check-node-typescript.yml
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read

concurrency:
  group: check-node-typescript-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          path: ./tmp
      - name: Set up Nix
        uses: ./tmp/.github/actions/setup-nix
        with:
          cachix-token: ${{ secrets.CACHIX_AUTH_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - run: nix flake new -t ./tmp#node-typescript ./work
      - name: Prepare the project
        working-directory: work
        run: |
          git init
          git add .

      - run: nix develop -L -c tsc --version
        working-directory: work
      - run: nix develop -L -c typescript-language-server --version
        working-directory: work
