name: Check flake-parts

on:
  push:
    paths:
    # Set this to the directory of the template
    - flake-parts/**
    - .github/workflows/check-flake-parts.yml
  workflow_dispatch:
  workflow_call:

concurrency:
  group: check-flake-parts-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: cachix/install-nix-action@02a151ada4993995686f9ed4f1be7cfbb229e56f # v31
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      with:
        path: ./tmp
    - run: nix flake new -t ./tmp#flake-parts ./work
    - name: Prepare the project
      working-directory: work
      run: |
        git init
        git add .

    - run: nix flake show
      working-directory: work
