name: Check gleam

on:
  push:
    paths:
      # Set this to the directory of the template
      - gleam/**
      - .github/workflows/check-gleam.yml
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read

concurrency:
  group: check-gleam-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          path: ./tmp
      - name: Set up Nix
        uses: ./tmp/.github/actions/setup-nix
        with:
          cachix-token: ${{ secrets.CACHIX_AUTH_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Initialize a project
        run: |
          nix run nixpkgs#gleam -- new hello_gleam
          cd hello_gleam
          nix flake init -t ../tmp#gleam

      - name: Prepare the project
        working-directory: hello_gleam
        run: |
          git init
          git add .

      - name: Run the example program
        working-directory: hello_gleam
        run: |
          nix develop -L --command gleam --version
          nix develop -L --command gleam run
