name: Check rust

on:
  push:
    paths:
      # Set this to the directory of the template
      - rust/**
      - .github/workflows/check-rust.yml
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read

concurrency:
  group: check-rust-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          path: ./tmp
      - name: Set up Nix
        uses: ./tmp/.github/actions/setup-nix
        with:
          cachix-token: ${{ secrets.CACHIX_AUTH_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - run: nix flake new -t ./tmp#rust ./work
      - name: Prepare the project
        working-directory: work
        run: |
          git init
          git add .

      - name: Check executables
        run: |
          nix develop -L --command rustc --version
          nix develop -L --command cargo --version
          nix develop -L --command rust-analyzer --version
          # shellcheck disable=SC2016
          nix develop -L --command sh -c 'test -d ${RUST_SRC_PATH}'
        working-directory: work
