name: Check flake-parts

on:
  push:
    paths:
      # Set this to the directory of the template
      - flake-parts/**
      - .github/workflows/check-flake-parts.yml
  workflow_dispatch:
  workflow_call:

concurrency:
  group: check-flake-parts-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
          path: ./tmp
      - name: Set up Nix
        uses: ./tmp/.github/actions/setup-nix
        with:
          cachix-token: ${{ secrets.CACHIX_AUTH_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - run: nix flake new -t ./tmp#flake-parts ./work
      - name: Prepare the project
        working-directory: work
        run: |
          git init
          git add .

      - run: nix flake show
        working-directory: work
