name: Check typescript-effect

on:
  push:
    paths:
    - typescript-effect/**
    - .github/workflows/check-typescript-effect.yml
  workflow_dispatch:
  workflow_call:

concurrency:
  group: check-typescript-effect-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: cachix/install-nix-action@fd24c48048070c1be9acd18c9d369a83f0fe94d7 # v31
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      with:
        path: ./tmp
    - run: nix flake new -t ./tmp#typescript-effect ./work
    - name: Prepare the project
      working-directory: work
      run: |
        git init
        git add .

    - run: nix develop -L -c tsc --version
      working-directory: work
    - run: nix develop -L -c typescript-language-server --version
      working-directory: work
