name: Check license

permissions:
  contents: read

on:
  pull_request:
    # This ignore list does not cover the entire set of irrelevant files, but it
    # saves resources in many cases.
    paths-ignore:
      - '.github/**'
      - '*.md'
      - '**/*.lock'
      - '**/*.json'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      # - uses: tj-actions/changed-files@dcc7a0cba800f454d79fff4b993e8c3555bcc0a8 # v45
      #   id: changed-files
      #   with:
      #     files_ignore: |
      #       /*.md
      #       **/*.lock
      #       **/*.json
      #       doc/*.*
      #       dev/**
      #       .github/**

      - uses: cachix/install-nix-action@616559265b40713947b9c190a8ff4b507b5df49b # v31

      - run: nix profile install nixpkgs#reuse

      - name: Check license
        run: 'reuse lint-file ${{ steps.changed-files.outputs.all_changed_files }}'
