name: Update

on:
  schedule:
    - cron: '0 4 * * 5'
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Set up Nix
        uses: ./.github/actions/setup-nix
        with:
          cachix-token: ${{ secrets.CACHIX_AUTH_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Erlang and Elixir
        run: nix run ./dev#update-beam --update-input nixpkgs --no-write-lock-file
        continue-on-error: true
        id: updated

      - name: Roll back if there is no modification
        run: git reset --hard ${{ github.sha }}
        if: ${{ steps.updated.outcome == 'failure' }}

      - uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8
        with:
          commit-message: 'Update'
          # Use a fine-grained personal access token that can trigger other
          # workflows
          token: ${{ secrets.PAT_FOR_PR }}
          base: master
          title: 'chore: Update flake inputs'
          branch: create-pull-request/update
          labels: automation,update
